name: Collect Notre Dame articles
on:
  workflow_dispatch: {}        # run it manually anytime
  schedule:
    - cron: "*/30 * * * *"     # and every 30 minutes (adjust as you like)

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # allow committing items.json back
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        run: python3 collect.py

      - name: Commit updated items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git commit -m "Update items.json [CI]" || echo "No changes to commit"
          git push
