name: Collect Notre Dame articles

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          python3 --version || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze

      - name: Run collector
        run: |
          set -x
          python3 collect.py
          echo "---- items.json head ----"
          head -n 40 items.json || true
          echo "---- items.json size ----"
          wc -c items.json || true

      - name: Commit updated items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git commit -m "Update items.json [CI]" || echo "No changes to commit"
          git push
