name: Collect Notre Dame articles

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 🔎 Find the directory that actually contains collect.py
      - name: Find project root
        id: findroot
        shell: bash
        run: |
          set -e
          ROOT="$(git rev-parse --show-toplevel)"
          CANDIDATE="$(git ls-files | grep -E '(^|/)(collect\.py)$' | head -n1 || true)"
          if [ -z "$CANDIDATE" ]; then
            echo "collect.py not found in repo files!" >&2
            # Write a minimal items.json at repo root so site doesn't break
            echo '{"team":"Notre Dame Football","updated":0,"count":0,"items":[]}' > items.json
            echo "dir=$ROOT" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          DIR="$(dirname "$CANDIDATE")"
          if [ "$DIR" = "." ]; then DIR="$ROOT"; else DIR="$ROOT/$DIR"; fi
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"
          echo "Detected project dir: $DIR"

      - name: Show tree
        shell: bash
        run: |
          echo "Working dir: ${{ steps.findroot.outputs.dir }}"
          ls -la "${{ steps.findroot.outputs.dir }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ${{ steps.findroot.outputs.dir }}
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install feedparser requests || true

      # 🚛 Run collector (never fail the job; it writes items.json no matter what)
      - name: Run collector
        working-directory: ${{ steps.findroot.outputs.dir }}
        shell: bash
        run: |
          set -x
          python3 collect.py || true
          echo "---- items.json head ----"
          head -n 40 items.json || true
          echo "---- items.json size ----"
          wc -c items.json || true

      - name: Commit updated items.json
        working-directory: ${{ steps.findroot.outputs.dir }}
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git commit -m "Update items.json [CI]" || echo "No changes to commit"
          git push || true
